// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medication.proto

package com.ps.assignment3;

public final class MedicationOuterClass {
  private MedicationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ps.assignment3.MedicationOuterClass.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ps.assignment3.MedicationOuterClass.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ps.assignment3.MedicationOuterClass.Empty.class, com.ps.assignment3.MedicationOuterClass.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ps.assignment3.MedicationOuterClass.Empty)) {
        return super.equals(obj);
      }
      com.ps.assignment3.MedicationOuterClass.Empty other = (com.ps.assignment3.MedicationOuterClass.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ps.assignment3.MedicationOuterClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        com.ps.assignment3.MedicationOuterClass.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ps.assignment3.MedicationOuterClass.Empty.class, com.ps.assignment3.MedicationOuterClass.Empty.Builder.class);
      }

      // Construct using com.ps.assignment3.MedicationOuterClass.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.Empty getDefaultInstanceForType() {
        return com.ps.assignment3.MedicationOuterClass.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.Empty build() {
        com.ps.assignment3.MedicationOuterClass.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.Empty buildPartial() {
        com.ps.assignment3.MedicationOuterClass.Empty result = new com.ps.assignment3.MedicationOuterClass.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ps.assignment3.MedicationOuterClass.Empty) {
          return mergeFrom((com.ps.assignment3.MedicationOuterClass.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ps.assignment3.MedicationOuterClass.Empty other) {
        if (other == com.ps.assignment3.MedicationOuterClass.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ps.assignment3.MedicationOuterClass.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ps.assignment3.MedicationOuterClass.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final com.ps.assignment3.MedicationOuterClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ps.assignment3.MedicationOuterClass.Empty();
    }

    public static com.ps.assignment3.MedicationOuterClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ps.assignment3.MedicationOuterClass.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IdMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IdMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 medicationId = 1;</code>
     */
    int getMedicationId();
  }
  /**
   * Protobuf type {@code IdMessage}
   */
  public  static final class IdMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IdMessage)
      IdMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdMessage.newBuilder() to construct.
    private IdMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdMessage() {
      medicationId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IdMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              medicationId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ps.assignment3.MedicationOuterClass.internal_static_IdMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ps.assignment3.MedicationOuterClass.internal_static_IdMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ps.assignment3.MedicationOuterClass.IdMessage.class, com.ps.assignment3.MedicationOuterClass.IdMessage.Builder.class);
    }

    public static final int MEDICATIONID_FIELD_NUMBER = 1;
    private int medicationId_;
    /**
     * <code>int32 medicationId = 1;</code>
     */
    public int getMedicationId() {
      return medicationId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (medicationId_ != 0) {
        output.writeInt32(1, medicationId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (medicationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, medicationId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ps.assignment3.MedicationOuterClass.IdMessage)) {
        return super.equals(obj);
      }
      com.ps.assignment3.MedicationOuterClass.IdMessage other = (com.ps.assignment3.MedicationOuterClass.IdMessage) obj;

      boolean result = true;
      result = result && (getMedicationId()
          == other.getMedicationId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDICATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getMedicationId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.IdMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ps.assignment3.MedicationOuterClass.IdMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IdMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IdMessage)
        com.ps.assignment3.MedicationOuterClass.IdMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_IdMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_IdMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ps.assignment3.MedicationOuterClass.IdMessage.class, com.ps.assignment3.MedicationOuterClass.IdMessage.Builder.class);
      }

      // Construct using com.ps.assignment3.MedicationOuterClass.IdMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        medicationId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_IdMessage_descriptor;
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.IdMessage getDefaultInstanceForType() {
        return com.ps.assignment3.MedicationOuterClass.IdMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.IdMessage build() {
        com.ps.assignment3.MedicationOuterClass.IdMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.IdMessage buildPartial() {
        com.ps.assignment3.MedicationOuterClass.IdMessage result = new com.ps.assignment3.MedicationOuterClass.IdMessage(this);
        result.medicationId_ = medicationId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ps.assignment3.MedicationOuterClass.IdMessage) {
          return mergeFrom((com.ps.assignment3.MedicationOuterClass.IdMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ps.assignment3.MedicationOuterClass.IdMessage other) {
        if (other == com.ps.assignment3.MedicationOuterClass.IdMessage.getDefaultInstance()) return this;
        if (other.getMedicationId() != 0) {
          setMedicationId(other.getMedicationId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ps.assignment3.MedicationOuterClass.IdMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ps.assignment3.MedicationOuterClass.IdMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int medicationId_ ;
      /**
       * <code>int32 medicationId = 1;</code>
       */
      public int getMedicationId() {
        return medicationId_;
      }
      /**
       * <code>int32 medicationId = 1;</code>
       */
      public Builder setMedicationId(int value) {
        
        medicationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 medicationId = 1;</code>
       */
      public Builder clearMedicationId() {
        
        medicationId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IdMessage)
    }

    // @@protoc_insertion_point(class_scope:IdMessage)
    private static final com.ps.assignment3.MedicationOuterClass.IdMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ps.assignment3.MedicationOuterClass.IdMessage();
    }

    public static com.ps.assignment3.MedicationOuterClass.IdMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdMessage>
        PARSER = new com.google.protobuf.AbstractParser<IdMessage>() {
      @java.lang.Override
      public IdMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IdMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IdMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IdMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ps.assignment3.MedicationOuterClass.IdMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MedicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Medication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 medicationId = 1;</code>
     */
    int getMedicationId();

    /**
     * <code>string description = 2;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string start = 3;</code>
     */
    java.lang.String getStart();
    /**
     * <code>string start = 3;</code>
     */
    com.google.protobuf.ByteString
        getStartBytes();

    /**
     * <code>string end = 4;</code>
     */
    java.lang.String getEnd();
    /**
     * <code>string end = 4;</code>
     */
    com.google.protobuf.ByteString
        getEndBytes();
  }
  /**
   * Protobuf type {@code Medication}
   */
  public  static final class Medication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Medication)
      MedicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Medication.newBuilder() to construct.
    private Medication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Medication() {
      medicationId_ = 0;
      description_ = "";
      start_ = "";
      end_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Medication(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              medicationId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              start_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              end_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ps.assignment3.MedicationOuterClass.internal_static_Medication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ps.assignment3.MedicationOuterClass.internal_static_Medication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ps.assignment3.MedicationOuterClass.Medication.class, com.ps.assignment3.MedicationOuterClass.Medication.Builder.class);
    }

    public static final int MEDICATIONID_FIELD_NUMBER = 1;
    private int medicationId_;
    /**
     * <code>int32 medicationId = 1;</code>
     */
    public int getMedicationId() {
      return medicationId_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_FIELD_NUMBER = 3;
    private volatile java.lang.Object start_;
    /**
     * <code>string start = 3;</code>
     */
    public java.lang.String getStart() {
      java.lang.Object ref = start_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        start_ = s;
        return s;
      }
    }
    /**
     * <code>string start = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStartBytes() {
      java.lang.Object ref = start_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        start_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int END_FIELD_NUMBER = 4;
    private volatile java.lang.Object end_;
    /**
     * <code>string end = 4;</code>
     */
    public java.lang.String getEnd() {
      java.lang.Object ref = end_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        end_ = s;
        return s;
      }
    }
    /**
     * <code>string end = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEndBytes() {
      java.lang.Object ref = end_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        end_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (medicationId_ != 0) {
        output.writeInt32(1, medicationId_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      if (!getStartBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, start_);
      }
      if (!getEndBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, end_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (medicationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, medicationId_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      if (!getStartBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, start_);
      }
      if (!getEndBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, end_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ps.assignment3.MedicationOuterClass.Medication)) {
        return super.equals(obj);
      }
      com.ps.assignment3.MedicationOuterClass.Medication other = (com.ps.assignment3.MedicationOuterClass.Medication) obj;

      boolean result = true;
      result = result && (getMedicationId()
          == other.getMedicationId());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && getStart()
          .equals(other.getStart());
      result = result && getEnd()
          .equals(other.getEnd());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDICATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getMedicationId();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart().hashCode();
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + getEnd().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.Medication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ps.assignment3.MedicationOuterClass.Medication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Medication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Medication)
        com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_Medication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_Medication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ps.assignment3.MedicationOuterClass.Medication.class, com.ps.assignment3.MedicationOuterClass.Medication.Builder.class);
      }

      // Construct using com.ps.assignment3.MedicationOuterClass.Medication.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        medicationId_ = 0;

        description_ = "";

        start_ = "";

        end_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_Medication_descriptor;
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.Medication getDefaultInstanceForType() {
        return com.ps.assignment3.MedicationOuterClass.Medication.getDefaultInstance();
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.Medication build() {
        com.ps.assignment3.MedicationOuterClass.Medication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.Medication buildPartial() {
        com.ps.assignment3.MedicationOuterClass.Medication result = new com.ps.assignment3.MedicationOuterClass.Medication(this);
        result.medicationId_ = medicationId_;
        result.description_ = description_;
        result.start_ = start_;
        result.end_ = end_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ps.assignment3.MedicationOuterClass.Medication) {
          return mergeFrom((com.ps.assignment3.MedicationOuterClass.Medication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ps.assignment3.MedicationOuterClass.Medication other) {
        if (other == com.ps.assignment3.MedicationOuterClass.Medication.getDefaultInstance()) return this;
        if (other.getMedicationId() != 0) {
          setMedicationId(other.getMedicationId());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getStart().isEmpty()) {
          start_ = other.start_;
          onChanged();
        }
        if (!other.getEnd().isEmpty()) {
          end_ = other.end_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ps.assignment3.MedicationOuterClass.Medication parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ps.assignment3.MedicationOuterClass.Medication) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int medicationId_ ;
      /**
       * <code>int32 medicationId = 1;</code>
       */
      public int getMedicationId() {
        return medicationId_;
      }
      /**
       * <code>int32 medicationId = 1;</code>
       */
      public Builder setMedicationId(int value) {
        
        medicationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 medicationId = 1;</code>
       */
      public Builder clearMedicationId() {
        
        medicationId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object start_ = "";
      /**
       * <code>string start = 3;</code>
       */
      public java.lang.String getStart() {
        java.lang.Object ref = start_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          start_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string start = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStartBytes() {
        java.lang.Object ref = start_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          start_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string start = 3;</code>
       */
      public Builder setStart(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string start = 3;</code>
       */
      public Builder clearStart() {
        
        start_ = getDefaultInstance().getStart();
        onChanged();
        return this;
      }
      /**
       * <code>string start = 3;</code>
       */
      public Builder setStartBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        start_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object end_ = "";
      /**
       * <code>string end = 4;</code>
       */
      public java.lang.String getEnd() {
        java.lang.Object ref = end_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          end_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string end = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEndBytes() {
        java.lang.Object ref = end_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          end_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string end = 4;</code>
       */
      public Builder setEnd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string end = 4;</code>
       */
      public Builder clearEnd() {
        
        end_ = getDefaultInstance().getEnd();
        onChanged();
        return this;
      }
      /**
       * <code>string end = 4;</code>
       */
      public Builder setEndBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        end_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Medication)
    }

    // @@protoc_insertion_point(class_scope:Medication)
    private static final com.ps.assignment3.MedicationOuterClass.Medication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ps.assignment3.MedicationOuterClass.Medication();
    }

    public static com.ps.assignment3.MedicationOuterClass.Medication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Medication>
        PARSER = new com.google.protobuf.AbstractParser<Medication>() {
      @java.lang.Override
      public Medication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Medication(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Medication> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Medication> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ps.assignment3.MedicationOuterClass.Medication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MedicationListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MedicationList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    java.util.List<com.ps.assignment3.MedicationOuterClass.Medication> 
        getMedsList();
    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    com.ps.assignment3.MedicationOuterClass.Medication getMeds(int index);
    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    int getMedsCount();
    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    java.util.List<? extends com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder> 
        getMedsOrBuilderList();
    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder getMedsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MedicationList}
   */
  public  static final class MedicationList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MedicationList)
      MedicationListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MedicationList.newBuilder() to construct.
    private MedicationList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MedicationList() {
      meds_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MedicationList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                meds_ = new java.util.ArrayList<com.ps.assignment3.MedicationOuterClass.Medication>();
                mutable_bitField0_ |= 0x00000001;
              }
              meds_.add(
                  input.readMessage(com.ps.assignment3.MedicationOuterClass.Medication.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          meds_ = java.util.Collections.unmodifiableList(meds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ps.assignment3.MedicationOuterClass.internal_static_MedicationList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ps.assignment3.MedicationOuterClass.internal_static_MedicationList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ps.assignment3.MedicationOuterClass.MedicationList.class, com.ps.assignment3.MedicationOuterClass.MedicationList.Builder.class);
    }

    public static final int MEDS_FIELD_NUMBER = 1;
    private java.util.List<com.ps.assignment3.MedicationOuterClass.Medication> meds_;
    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    public java.util.List<com.ps.assignment3.MedicationOuterClass.Medication> getMedsList() {
      return meds_;
    }
    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    public java.util.List<? extends com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder> 
        getMedsOrBuilderList() {
      return meds_;
    }
    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    public int getMedsCount() {
      return meds_.size();
    }
    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    public com.ps.assignment3.MedicationOuterClass.Medication getMeds(int index) {
      return meds_.get(index);
    }
    /**
     * <code>repeated .Medication meds = 1;</code>
     */
    public com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder getMedsOrBuilder(
        int index) {
      return meds_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < meds_.size(); i++) {
        output.writeMessage(1, meds_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < meds_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, meds_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ps.assignment3.MedicationOuterClass.MedicationList)) {
        return super.equals(obj);
      }
      com.ps.assignment3.MedicationOuterClass.MedicationList other = (com.ps.assignment3.MedicationOuterClass.MedicationList) obj;

      boolean result = true;
      result = result && getMedsList()
          .equals(other.getMedsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMedsCount() > 0) {
        hash = (37 * hash) + MEDS_FIELD_NUMBER;
        hash = (53 * hash) + getMedsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ps.assignment3.MedicationOuterClass.MedicationList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ps.assignment3.MedicationOuterClass.MedicationList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MedicationList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MedicationList)
        com.ps.assignment3.MedicationOuterClass.MedicationListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_MedicationList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_MedicationList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ps.assignment3.MedicationOuterClass.MedicationList.class, com.ps.assignment3.MedicationOuterClass.MedicationList.Builder.class);
      }

      // Construct using com.ps.assignment3.MedicationOuterClass.MedicationList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMedsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (medsBuilder_ == null) {
          meds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          medsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ps.assignment3.MedicationOuterClass.internal_static_MedicationList_descriptor;
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.MedicationList getDefaultInstanceForType() {
        return com.ps.assignment3.MedicationOuterClass.MedicationList.getDefaultInstance();
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.MedicationList build() {
        com.ps.assignment3.MedicationOuterClass.MedicationList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ps.assignment3.MedicationOuterClass.MedicationList buildPartial() {
        com.ps.assignment3.MedicationOuterClass.MedicationList result = new com.ps.assignment3.MedicationOuterClass.MedicationList(this);
        int from_bitField0_ = bitField0_;
        if (medsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            meds_ = java.util.Collections.unmodifiableList(meds_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.meds_ = meds_;
        } else {
          result.meds_ = medsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ps.assignment3.MedicationOuterClass.MedicationList) {
          return mergeFrom((com.ps.assignment3.MedicationOuterClass.MedicationList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ps.assignment3.MedicationOuterClass.MedicationList other) {
        if (other == com.ps.assignment3.MedicationOuterClass.MedicationList.getDefaultInstance()) return this;
        if (medsBuilder_ == null) {
          if (!other.meds_.isEmpty()) {
            if (meds_.isEmpty()) {
              meds_ = other.meds_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMedsIsMutable();
              meds_.addAll(other.meds_);
            }
            onChanged();
          }
        } else {
          if (!other.meds_.isEmpty()) {
            if (medsBuilder_.isEmpty()) {
              medsBuilder_.dispose();
              medsBuilder_ = null;
              meds_ = other.meds_;
              bitField0_ = (bitField0_ & ~0x00000001);
              medsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMedsFieldBuilder() : null;
            } else {
              medsBuilder_.addAllMessages(other.meds_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ps.assignment3.MedicationOuterClass.MedicationList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ps.assignment3.MedicationOuterClass.MedicationList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ps.assignment3.MedicationOuterClass.Medication> meds_ =
        java.util.Collections.emptyList();
      private void ensureMedsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          meds_ = new java.util.ArrayList<com.ps.assignment3.MedicationOuterClass.Medication>(meds_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ps.assignment3.MedicationOuterClass.Medication, com.ps.assignment3.MedicationOuterClass.Medication.Builder, com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder> medsBuilder_;

      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public java.util.List<com.ps.assignment3.MedicationOuterClass.Medication> getMedsList() {
        if (medsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(meds_);
        } else {
          return medsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public int getMedsCount() {
        if (medsBuilder_ == null) {
          return meds_.size();
        } else {
          return medsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public com.ps.assignment3.MedicationOuterClass.Medication getMeds(int index) {
        if (medsBuilder_ == null) {
          return meds_.get(index);
        } else {
          return medsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public Builder setMeds(
          int index, com.ps.assignment3.MedicationOuterClass.Medication value) {
        if (medsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMedsIsMutable();
          meds_.set(index, value);
          onChanged();
        } else {
          medsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public Builder setMeds(
          int index, com.ps.assignment3.MedicationOuterClass.Medication.Builder builderForValue) {
        if (medsBuilder_ == null) {
          ensureMedsIsMutable();
          meds_.set(index, builderForValue.build());
          onChanged();
        } else {
          medsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public Builder addMeds(com.ps.assignment3.MedicationOuterClass.Medication value) {
        if (medsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMedsIsMutable();
          meds_.add(value);
          onChanged();
        } else {
          medsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public Builder addMeds(
          int index, com.ps.assignment3.MedicationOuterClass.Medication value) {
        if (medsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMedsIsMutable();
          meds_.add(index, value);
          onChanged();
        } else {
          medsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public Builder addMeds(
          com.ps.assignment3.MedicationOuterClass.Medication.Builder builderForValue) {
        if (medsBuilder_ == null) {
          ensureMedsIsMutable();
          meds_.add(builderForValue.build());
          onChanged();
        } else {
          medsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public Builder addMeds(
          int index, com.ps.assignment3.MedicationOuterClass.Medication.Builder builderForValue) {
        if (medsBuilder_ == null) {
          ensureMedsIsMutable();
          meds_.add(index, builderForValue.build());
          onChanged();
        } else {
          medsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public Builder addAllMeds(
          java.lang.Iterable<? extends com.ps.assignment3.MedicationOuterClass.Medication> values) {
        if (medsBuilder_ == null) {
          ensureMedsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, meds_);
          onChanged();
        } else {
          medsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public Builder clearMeds() {
        if (medsBuilder_ == null) {
          meds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          medsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public Builder removeMeds(int index) {
        if (medsBuilder_ == null) {
          ensureMedsIsMutable();
          meds_.remove(index);
          onChanged();
        } else {
          medsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public com.ps.assignment3.MedicationOuterClass.Medication.Builder getMedsBuilder(
          int index) {
        return getMedsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder getMedsOrBuilder(
          int index) {
        if (medsBuilder_ == null) {
          return meds_.get(index);  } else {
          return medsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public java.util.List<? extends com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder> 
           getMedsOrBuilderList() {
        if (medsBuilder_ != null) {
          return medsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(meds_);
        }
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public com.ps.assignment3.MedicationOuterClass.Medication.Builder addMedsBuilder() {
        return getMedsFieldBuilder().addBuilder(
            com.ps.assignment3.MedicationOuterClass.Medication.getDefaultInstance());
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public com.ps.assignment3.MedicationOuterClass.Medication.Builder addMedsBuilder(
          int index) {
        return getMedsFieldBuilder().addBuilder(
            index, com.ps.assignment3.MedicationOuterClass.Medication.getDefaultInstance());
      }
      /**
       * <code>repeated .Medication meds = 1;</code>
       */
      public java.util.List<com.ps.assignment3.MedicationOuterClass.Medication.Builder> 
           getMedsBuilderList() {
        return getMedsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ps.assignment3.MedicationOuterClass.Medication, com.ps.assignment3.MedicationOuterClass.Medication.Builder, com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder> 
          getMedsFieldBuilder() {
        if (medsBuilder_ == null) {
          medsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ps.assignment3.MedicationOuterClass.Medication, com.ps.assignment3.MedicationOuterClass.Medication.Builder, com.ps.assignment3.MedicationOuterClass.MedicationOrBuilder>(
                  meds_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          meds_ = null;
        }
        return medsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MedicationList)
    }

    // @@protoc_insertion_point(class_scope:MedicationList)
    private static final com.ps.assignment3.MedicationOuterClass.MedicationList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ps.assignment3.MedicationOuterClass.MedicationList();
    }

    public static com.ps.assignment3.MedicationOuterClass.MedicationList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MedicationList>
        PARSER = new com.google.protobuf.AbstractParser<MedicationList>() {
      @java.lang.Override
      public MedicationList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MedicationList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MedicationList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MedicationList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ps.assignment3.MedicationOuterClass.MedicationList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IdMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IdMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Medication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Medication_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MedicationList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MedicationList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020medication.proto\"\007\n\005Empty\"!\n\tIdMessage" +
      "\022\024\n\014medicationId\030\001 \001(\005\"S\n\nMedication\022\024\n\014" +
      "medicationId\030\001 \001(\005\022\023\n\013description\030\002 \001(\t\022" +
      "\r\n\005start\030\003 \001(\t\022\013\n\003end\030\004 \001(\t\"+\n\016Medicatio" +
      "nList\022\031\n\004meds\030\001 \003(\0132\013.Medication2u\n\nmedi" +
      "cation\022!\n\006getAll\022\006.Empty\032\017.MedicationLis" +
      "t\022\"\n\007getById\022\n.IdMessage\032\013.Medication\022 \n" +
      "\ndeleteById\022\n.IdMessage\032\006.EmptyB\024\n\022com.p" +
      "s.assignment3b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_IdMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IdMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IdMessage_descriptor,
        new java.lang.String[] { "MedicationId", });
    internal_static_Medication_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Medication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Medication_descriptor,
        new java.lang.String[] { "MedicationId", "Description", "Start", "End", });
    internal_static_MedicationList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MedicationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MedicationList_descriptor,
        new java.lang.String[] { "Meds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
